/**
 * edRegistry.ts
 *
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
 * Regenerate by running 'node scripts/sync-ed.js' or via npm scripts.
 */

import { parseEdFile } from "../../presentation/routes/pages/projects/ProjectViewer";
import type { EdFile } from "./projectViewerConstant";

// ─── RAW .ED SOURCES ──────────────────────────────────────────────────────────

const RAW_12_pamana = `
project-details = {
	active: true,
	featured: false,
	status: "ARCHIVED",
	title:"PAMANA",
	subtitle:"AI-powered itinerary creator that generates personalized travel plans based on user preferences, budget, and interests."
	hero-image:"/hero-pamana.png",
	stats:[
		{ label: "NODES RENDERED", value: "1.0M+" },
		{ label: "SUSTAINED FRAMERATE", value: "60FPS" },
		{ label: "HN FRONT PAGE", value: "800+ ⇧" },
	  ],
	client-type:"COMPETITION",
	date:"FEBRUARY 2026",
	technologies:["REACT", "ARTIFICIAL INTELLIGENCE"],
	links: [
		{ label: "VIEW REPOSITORY", href: "#" },
		{ label: "LIVE DEMO", href: "#" },
	  ],
	bestFitService: {
		icon: "◆",
		title: "NATIVE APP DEVELOPMENT",
		subtitle: "High-performance apps built close to the metal, tuned for the platform they ship on.",
		link: "#"
	}
}`;

const RAW_11_shroomify = `
project-details = {
	active: true,
	featured: true,
	status: "OSS",
	title:"SHROOMIFY",
	subtitle:"Image-based contamination classification using Modified Feature Engineering and Artificial Neural Networks"
	hero-image:"/hero-shroomify.png",
	stats:[
		{ label: "NODES RENDERED", value: "1.0M+" },
		{ label: "SUSTAINED FRAMERATE", value: "60FPS" },
		{ label: "HN FRONT PAGE", value: "800+ ⇧" },
	  ],
	client-type:"THESIS",
	date:"JANUARY 2026",
	technologies:["PYTHON", "MACHINE LEARNING", "REACT", "TYPESCRIPT"],
	links: [
		{ label: "VIEW REPOSITORY", href: "#" },
		{ label: "LIVE DEMO", href: "#" },
	  ],
	bestFitService: {
		icon: "◆",
		title: "NATIVE APP DEVELOPMENT",
		subtitle: "High-performance apps built close to the metal, tuned for the platform they ship on.",
		link: "#"
	}
}`;

const RAW_10_werspaldo = `
project-details = {
	active: false,
	featured: false,
	status: "",
	title:"WER'S PALDO",
	subtitle:""
	hero-image:"",
	stats:[
		{ label: "NODES RENDERED", value: "1.0M+" },
		{ label: "SUSTAINED FRAMERATE", value: "60FPS" },
		{ label: "HN FRONT PAGE", value: "800+ ⇧" },
	  ],
	client-type:"COMPETITION",
	date:"JULY 2025",
	technologies:["BLOCKCHAIN", "REACT"],
	links: [
		{ label: "VIEW REPOSITORY", href: "#" },
		{ label: "LIVE DEMO", href: "#" },
	  ],
	bestFitService: {
		icon: "◆",
		title: "NATIVE APP DEVELOPMENT",
		subtitle: "High-performance apps built close to the metal, tuned for the platform they ship on.",
		link: "#"
	}
}`;

const RAW_09_virtuosense = `
project-details = {
	active: false,
	featured: false,
	status: "",
	title:"VIRTUOSENSE",
	subtitle:""
	hero-image:"",
	stats:[
		{ label: "NODES RENDERED", value: "1.0M+" },
		{ label: "SUSTAINED FRAMERATE", value: "60FPS" },
		{ label: "HN FRONT PAGE", value: "800+ ⇧" },
	  ],
	client-type:"",
	date:"",
	technologies:["MACHINE LEARNING", "JAVA", "ANROID STUDIO"],
	links: [
		{ label: "VIEW REPOSITORY", href: "#" },
		{ label: "LIVE DEMO", href: "#" },
	  ],
	bestFitService: {
		icon: "◆",
		title: "NATIVE APP DEVELOPMENT",
		subtitle: "High-performance apps built close to the metal, tuned for the platform they ship on.",
		link: "#"
	}
}`;

const RAW_08_codenames = `
project-details = {
	active: true,
	featured: false,
	status: "ACTIVE",
	title:"CODENAMES",
	subtitle:""
	hero-image:"/hero-codenames.png",
	stats:[
		{ label: "NODES RENDERED", value: "1.0M+" },
		{ label: "SUSTAINED FRAMERATE", value: "60FPS" },
		{ label: "HN FRONT PAGE", value: "800+ ⇧" },
	  ],
	client-type:"",
	date:"",
	technologies:["REACT", "TYPESCRIPT"],
	links: [
		{ label: "VIEW REPOSITORY", href: "#" },
		{ label: "LIVE DEMO", href: "#" },
	  ],
	bestFitService: {
		icon: "◆",
		title: "NATIVE APP DEVELOPMENT",
		subtitle: "High-performance apps built close to the metal, tuned for the platform they ship on.",
		link: "#"
	}
}`;

const RAW_07_pw = `
project-details = {
	active: false,
	featured: true,
	status: "",
	title:"PIYU WALLET",
	subtitle:""
	hero-image:"/hero-piyuwallet.png",
	stats:[
		{ label: "NODES RENDERED", value: "1.0M+" },
		{ label: "SUSTAINED FRAMERATE", value: "60FPS" },
		{ label: "HN FRONT PAGE", value: "800+ ⇧" },
	  ],
	client-type:"",
	date:"",
	technologies:["JAVA", "ANDROID STUDIO"],
	links: [
		{ label: "VIEW REPOSITORY", href: "#" },
		{ label: "LIVE DEMO", href: "#" },
	  ],
	bestFitService: {
		icon: "◆",
		title: "NATIVE APP DEVELOPMENT",
		subtitle: "High-performance apps built close to the metal, tuned for the platform they ship on.",
		link: "#"
	}
}`;

const RAW_06_roomba = `
project-details = {
	active: false,
	featured: false,
	status: "OSS",
	title:"ROOMBHIE THE ROOMBA",
	subtitle:""
	hero-image:"",
	stats:[
		{ label: "NODES RENDERED", value: "1.0M+" },
		{ label: "SUSTAINED FRAMERATE", value: "60FPS" },
		{ label: "HN FRONT PAGE", value: "800+ ⇧" },
	  ],
	client-type:"",
	date:"JANUARY 2025",
	technologies:["C", "PYTHON"],
	links: [
		{ label: "VIEW REPOSITORY", href: "#" },
		{ label: "LIVE DEMO", href: "#" },
	  ],
	bestFitService: {
		icon: "◆",
		title: "NATIVE APP DEVELOPMENT",
		subtitle: "High-performance apps built close to the metal, tuned for the platform they ship on.",
		link: "#"
	}
}`;

const RAW_05_itec = `
project-details = {
	active: false,
	featured: false,
	status: "",
	title:"TYPOGRAPHY ACTIVITY",
	subtitle:""
	hero-image:"/hero-itec.png",
	stats:[
		{ label: "NODES RENDERED", value: "1.0M+" },
		{ label: "SUSTAINED FRAMERATE", value: "60FPS" },
		{ label: "HN FRONT PAGE", value: "800+ ⇧" },
	  ],
	client-type:"",
	date:"APRIL 2024",
	technologies:["C++", "GLFW", "OPENGL"],
	links: [
		{ label: "VIEW REPOSITORY", href: "#" },
		{ label: "LIVE DEMO", href: "#" },
	  ],
	bestFitService: {
		icon: "◆",
		title: "NATIVE APP DEVELOPMENT",
		subtitle: "High-performance apps built close to the metal, tuned for the platform they ship on.",
		link: "#"
	}
}`;

const RAW_04_etala = `
project-details = {
	active: false,
	featured: false,
	status: "",
	title:"E-TALA",
	subtitle:""
	hero-image:"/hero-etala.png",
	stats:[
		{ label: "NODES RENDERED", value: "1.0M+" },
		{ label: "SUSTAINED FRAMERATE", value: "60FPS" },
		{ label: "HN FRONT PAGE", value: "800+ ⇧" },
	  ],
	client-type:"",
	date:"MARCH 2024",
	technologies:["JAVA", "ANDROID STUDIO"],
	links: [
		{ label: "VIEW REPOSITORY", href: "#" },
		{ label: "LIVE DEMO", href: "#" },
	  ],
	bestFitService: {
		icon: "◆",
		title: "NATIVE APP DEVELOPMENT",
		subtitle: "High-performance apps built close to the metal, tuned for the platform they ship on.",
		link: "#"
	}
}`;

const RAW_03_pw1 = `
project-details = {
	active: false,
	featured: false,
	status: "OSS",
	title:"Piyu Wallet (Legacy)",
	subtitle:"Digital banking platform for Laguna State Polytechnic University that enables secure cashless transactions using physical student IDs"
	hero-image:"/hero-pw1.png",
	stats:[
		{ label: "NODES RENDERED", value: "1.0M+" },
		{ label: "SUSTAINED FRAMERATE", value: "60FPS" },
		{ label: "HN FRONT PAGE", value: "800+ ⇧" },
	  ],
	client-type:"SCHOOL PROJECT",
	date:"MAY 2023",
	technologies:["C#"],
	links: [
		{ label: "VIEW REPOSITORY", href: "#" },
		{ label: "LIVE DEMO", href: "#" },
	  ],
	bestFitService: {
		icon: "◆",
		title: "NATIVE APP DEVELOPMENT",
		subtitle: "High-performance apps built close to the metal, tuned for the platform they ship on.",
		link: "#"
	}
}`;

const RAW_02_cafebistro = `
project-details = {
	active: false,
	featured: false,
	status: "ARCHIVED",
	title:"Cafe Bistro",
	subtitle:"point-of-sale (POS) system designed to simplify order management, billing, and daily operations for karinderias"
	hero-image:"/hero-cafebistro.png",
	stats:[
		{ label: "NODES RENDERED", value: "1.0M+" },
		{ label: "SUSTAINED FRAMERATE", value: "60FPS" },
		{ label: "HN FRONT PAGE", value: "800+ ⇧" },
	  ],
	client-type:"COMMISSION",
	date:"DECEMBER 2022",
	technologies:["C#", "POS"],
	links: [
		{ label: "VIEW REPOSITORY", href: "#" },
		{ label: "LIVE DEMO", href: "#" },
	  ],
	bestFitService: {
		icon: "◆",
		title: "NATIVE APP DEVELOPMENT",
		subtitle: "High-performance apps built close to the metal, tuned for the platform they ship on.",
		link: "#"
	}
}`;

const RAW_01_brewrikat = `
project-details = {
	active: false,
	featured: true,
	status: "OSS",
	title:"BREWRIKAT",
	subtitle:"point-of-sale (POS) system designed to streamline order processing, payments, and sales management for coffee shop"
	hero-image:"/hero-brewrikat.png",
	stats:[
		{ label: "NODES RENDERED", value: "1.0M+" },
		{ label: "SUSTAINED FRAMERATE", value: "60FPS" },
		{ label: "HN FRONT PAGE", value: "800+ ⇧" },
	  ],
	client-type:"SCHOOL PROJECT",
	date:"DECEMBER 2022",
	technologies:["C#", "POS"],
	links: [
		{ label: "VIEW REPOSITORY", href: "facebook.com" },
		{ label: "LIVE DEMO", href: "#" },
	  ],
	bestFitService: {
		icon: "◆",
		title: "NATIVE APP DEVELOPMENT",
		subtitle: "High-performance apps built close to the metal, tuned for the platform they ship on.",
		link: "#"
	}
}`;

// ─── REGISTRY ENTRY TYPE ──────────────────────────────────────────────────────

export type EdRegistryEntry = {
  /** Unique slug (matches the file prefix, e.g. "01_NEURAL_MESH") */
  slug: string;
  /** Raw .ed source text */
  raw: string;
};

/** Ordered list of all .ed project files. */
export const ED_REGISTRY: EdRegistryEntry[] = [
  { slug: "12_pamana",       raw: RAW_12_pamana },
  { slug: "11_shroomify",       raw: RAW_11_shroomify },
  { slug: "10_werspaldo",       raw: RAW_10_werspaldo },
  { slug: "09_virtuosense",       raw: RAW_09_virtuosense },
  { slug: "08_codenames",       raw: RAW_08_codenames },
  { slug: "07_pw",       raw: RAW_07_pw },
  { slug: "06_roomba",       raw: RAW_06_roomba },
  { slug: "05_itec",       raw: RAW_05_itec },
  { slug: "04_etala",       raw: RAW_04_etala },
  { slug: "03_pw1",       raw: RAW_03_pw1 },
  { slug: "02_cafebistro",       raw: RAW_02_cafebistro },
  { slug: "01_brewrikat",       raw: RAW_01_brewrikat },
];

// ─── PARSED CACHE ─────────────────────────────────────────────────────────────

export type ParsedEdEntry = {
  slug: string;
  data: EdFile;
};

let _parsed: ParsedEdEntry[] | null = null;

function slugOrder(slug: string): number {
  const m = slug.match(/^(\d+)_/);
  return m ? parseInt(m[1], 10) : 0;
}

/** Returns all .ed files parsed into EdFile structs, with memoisation. */
export function getAllParsedEdFiles(): ParsedEdEntry[] {
  if (_parsed) return _parsed;
  _parsed = ED_REGISTRY.map(({ slug, raw }) => ({
    slug,
    data: parseEdFile(raw),
  })).sort((a, b) => slugOrder(b.slug) - slugOrder(a.slug));
  return _parsed;
}

/** Find a parsed entry by slug. */
export function getEdBySlug(slug: string): ParsedEdEntry | undefined {
  return getAllParsedEdFiles().find((e) => e.slug === slug);
}

/** Find a parsed entry by project title (case-insensitive). */
export function getEdByTitle(title: string): ParsedEdEntry | undefined {
  const t = title.toLowerCase().replace(/[\s,]/g, "_");
  return getAllParsedEdFiles().find((e) =>
    e.slug.toLowerCase().includes(t) ||
    e.data.details.title.toLowerCase().replace(/[\s,]/g, "_") === t
  );
}

/** Find a parsed entry by the numeric id in the slug (e.g. "01"). */
export function getEdById(id: string): ParsedEdEntry | undefined {
  return getAllParsedEdFiles().find((e) => e.slug.startsWith(id + "_") || e.slug.startsWith(id.padStart(2, "0") + "_"));
}
