import type { CSSProperties } from "react";

export const footerStyles: Record<string, CSSProperties> = {
  footer: {
    borderTop: "1px solid #1a1a1a",
    padding: "44px 40px",
    display: "flex",
    flexDirection: "column",
    gap: 28,
  },
  topRow: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 24,
  },
  brandBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  socialRow: {
    display: "flex",
    alignItems: "center",
    gap: 0,
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  socialButton: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 11,
    color: "#333",
    letterSpacing: 2,
    textDecoration: "none",
    border: "1px solid #1a1a1a",
    borderRadius: 999,
    padding: "10px 12px",
    lineHeight: 1,
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "transparent",
  },
  navGrid: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 24,
  },
  navCol: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  navTitle: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 11,
    color: "#888",
    letterSpacing: 2,
  },
  navLinks: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  navLink: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 11,
    letterSpacing: 2,
    textDecoration: "none",
    width: "fit-content",
  },
  text: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 11,
    color: "#888",
    letterSpacing: 2,
  },
  cursor: {
    color: "#FFE600",
    animation: "blink 1s infinite",
    marginLeft: 4,
  },
};
