const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');

const projectsDir = path.join(__dirname, '..', 'src', 'presentation', 'routes', 'pages', 'projects');
const registryFile = path.join(__dirname, '..', 'src', 'utils', 'constants', 'edRegistry.ts');

function generateRegistry() {
  console.log('[sync-ed] Generating edRegistry.ts...');
  
  if (!fs.existsSync(projectsDir)) {
    console.error(`[sync-ed] Error: Projects directory not found at ${projectsDir}`);
    return;
  }

  // Get all .ed files starting with a numeric prefix
  const files = fs.readdirSync(projectsDir)
    .filter(file => file.endsWith('.ed') && /^\d+_/.test(file))
    .sort((a, b) => {
      const num = (name) => parseInt(name.match(/^(\d+)_/)[1], 10);
      return num(b) - num(a);
    });

  const entries = [];
  const definitions = [];

  for (const file of files) {
    const slug = path.basename(file, '.ed');
    const filePath = path.join(projectsDir, file);
    const content = fs.readFileSync(filePath, 'utf8');

    // Escape backslashes, backticks and template string syntax inside raw text
    const escapedContent = content
      .replace(/\\/g, '\\\\')
      .replace(/`/g, '\\`')
      .replace(/\${/g, '\\${');

    const constName = `RAW_${slug}`;
    definitions.push(`const ${constName} = \`\n${escapedContent}\`;`);
    entries.push(`  { slug: "${slug}",       raw: ${constName} },`);
  }

  const output = `/**
 * edRegistry.ts
 *
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
 * Regenerate by running 'node scripts/sync-ed.js' or via npm scripts.
 */

import { parseEdFile } from "../../presentation/routes/pages/projects/ProjectViewer";
import type { EdFile } from "./projectViewerConstant";

// ─── RAW .ED SOURCES ──────────────────────────────────────────────────────────

${definitions.join('\n\n')}

// ─── REGISTRY ENTRY TYPE ──────────────────────────────────────────────────────

export type EdRegistryEntry = {
  /** Unique slug (matches the file prefix, e.g. "01_NEURAL_MESH") */
  slug: string;
  /** Raw .ed source text */
  raw: string;
};

/** Ordered list of all .ed project files. */
export const ED_REGISTRY: EdRegistryEntry[] = [
${entries.join('\n')}
];

// ─── PARSED CACHE ─────────────────────────────────────────────────────────────

export type ParsedEdEntry = {
  slug: string;
  data: EdFile;
};

let _parsed: ParsedEdEntry[] | null = null;

function slugOrder(slug: string): number {
  const m = slug.match(/^(\\d+)_/);
  return m ? parseInt(m[1], 10) : 0;
}

/** Returns all .ed files parsed into EdFile structs, with memoisation. */
export function getAllParsedEdFiles(): ParsedEdEntry[] {
  if (_parsed) return _parsed;
  _parsed = ED_REGISTRY.map(({ slug, raw }) => ({
    slug,
    data: parseEdFile(raw),
  })).sort((a, b) => slugOrder(b.slug) - slugOrder(a.slug));
  return _parsed;
}

/** Find a parsed entry by slug. */
export function getEdBySlug(slug: string): ParsedEdEntry | undefined {
  return getAllParsedEdFiles().find((e) => e.slug === slug);
}

/** Find a parsed entry by project title (case-insensitive). */
export function getEdByTitle(title: string): ParsedEdEntry | undefined {
  const t = title.toLowerCase().replace(/[\\s,]/g, "_");
  return getAllParsedEdFiles().find((e) =>
    e.slug.toLowerCase().includes(t) ||
    e.data.details.title.toLowerCase().replace(/[\\s,]/g, "_") === t
  );
}

/** Find a parsed entry by the numeric id in the slug (e.g. "01"). */
export function getEdById(id: string): ParsedEdEntry | undefined {
  return getAllParsedEdFiles().find((e) => e.slug.startsWith(id + "_") || e.slug.startsWith(id.padStart(2, "0") + "_"));
}
`;

  fs.writeFileSync(registryFile, output, 'utf8');
  console.log(`[sync-ed] Successfully wrote ${files.length} project(s) to edRegistry.ts.`);
}

// Check for --watch flag
const isWatch = process.argv.includes('--watch');

// Always do initial generation
generateRegistry();

if (isWatch) {
  console.log('[sync-ed] Watching for changes to .ed files in projects directory...');
  
  let debounceTimeout = null;
  fs.watch(projectsDir, (eventType, filename) => {
    if (filename && filename.endsWith('.ed') && /^\d+_/.test(filename)) {
      if (debounceTimeout) clearTimeout(debounceTimeout);
      debounceTimeout = setTimeout(() => {
        console.log(`[sync-ed] Change detected in ${filename}. Rebuilding...`);
        try {
          generateRegistry();
        } catch (err) {
          console.error('[sync-ed] Error regenerating registry:', err);
        }
      }, 100);
    }
  });

  // Spawn react-scripts start
  console.log('[sync-ed] Starting CRA dev server (react-scripts start)...');
  const startProcess = spawn('npx', ['react-scripts', 'start'], {
    shell: true,
    stdio: 'inherit',
    cwd: path.join(__dirname, '..')
  });

  startProcess.on('close', (code) => {
    process.exit(code);
  });
}
